# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    # Look for GitHub Actions workflows in the `root` directory
    directory: "/"
    # Check the for updates once a week
    schedule:
      interval: "weekly"
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
  # Look for Go modules in the `root` directory
    directory: "/"
    schedule:
      interval: "weekly"