# Copyright 2025 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

name: Validate Changelog

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
      - 'v*.*'

jobs:
  validate-changelog:
    name: Validate Changelog
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-changelog') }}
    steps:
      - uses: actions/checkout@v6
      
      - uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47
        id: changed-files
        with:
          files: CHANGELOG.md

      - name: Check CHANGELOG.md updated
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "::error::CHANGELOG.md has not been updated. Please update the changelog or add the 'skip-changelog' label to opt out."
          exit 1

